# Enter your code here. Read input from STDIN. Print output to STDOUT
import math
AB = float(input())
BC = float(input())
angle = math.degrees(math.atan2(AB, BC))
print(str(round(angle))+'\N{DEGREE SIGN}')
# atan2(X,Y) can avoid the inaccuracy which is generated by X/Y if you use atan(X/Y).
